use crate::{Error, Result};
use std::str::FromStr;

pub struct Stat {
    pid: u32,
    comm: String,
    state: String,
    ppid: u32,
    pgid: u32,
    sid: u32,
    tty_nr: usize,
    tty_pgrp: usize,
    flags: usize,
    min_flt: usize,
    cmin_flt: usize,
    maj_flt: usize,
    cmaj_flt: usize,
    utime: usize,
    stime: usize,
    cutime: usize,
    cstime: usize,
    priority: usize,
    nice: usize,
    num_threads: usize,
    it_real_value: usize,
    start_time: usize,
    vsize: usize,
    rss: usize,
    rlim: usize,
    start_code: usize,
    end_code: usize,
    start_stack: usize,
    kstkesp: usize,
    kstkeip: usize,
    pendingsig: usize,
    block_sig: usize,
    sigign: usize,
    sigcatch: usize,
    wchan: usize,
    nswap: usize,
    cnswap: usize,
    exit_signal: usize,
    task_cpu: usize,
    task_rt_priority: usize,
    task_policy: usize,
    blio_ticks: usize,
    gtime: usize,
    cgtime: usize,
    start_data: usize,
    end_data: usize,
    start_brk: usize,
    arg_start: usize,
    arg_end: usize,
    env_start: usize,
    env_end: usize,
    exit_code: usize,
}

impl Stat {
    getter_gen! {
        pid: u32,
        comm: String,
        state: String,
        ppid: u32,
        pgid: u32,
        sid: u32,
        tty_nr: usize,
        tty_pgrp: usize,
        flags: usize,
        min_flt: usize,
        cmin_flt: usize,
        maj_flt: usize,
        cmaj_flt: usize,
        utime: usize,
        stime: usize,
        cutime: usize,
        cstime: usize,
        priority: usize,
        nice: usize,
        num_threads: usize,
        it_real_value: usize,
        start_time: usize,
        vsize: usize,
        rss: usize,
        rlim: usize,
        start_code: usize,
        end_code: usize,
        start_stack: usize,
        kstkesp: usize,
        kstkeip: usize,
        pendingsig: usize,
        block_sig: usize,
        sigign: usize,
        sigcatch: usize,
        wchan: usize,
        nswap: usize,
        cnswap: usize,
        exit_signal: usize,
        task_cpu: usize,
        task_rt_priority: usize,
        task_policy: usize,
        blio_ticks: usize,
        gtime: usize,
        cgtime: usize,
        start_data: usize,
        end_data: usize,
        start_brk: usize,
        arg_start: usize,
        arg_end: usize,
        env_start: usize,
        env_end: usize,
        exit_code: usize
    }
}
impl FromStr for Stat {
    type Err = Error;

    fn from_str(line: &str) -> Result<Stat> {
        let columns: Vec<&str> = line.split_ascii_whitespace().collect();
        if columns.len() != 52 {
            return Err(Error::BadFormat);
        }
        Ok(Stat {
            pid: columns[0].parse::<u32>()?,
            comm: columns[1].to_string(),
            state: columns[2].to_string(),
            ppid: columns[3].parse::<u32>()?,
            pgid: columns[4].parse::<u32>()?,
            sid: columns[5].parse::<u32>()?,
            tty_nr: columns[6].parse::<usize>()?,
            tty_pgrp: columns[7].parse::<usize>()?,
            flags: columns[8].parse::<usize>()?,
            min_flt: columns[9].parse::<usize>()?,
            cmin_flt: columns[10].parse::<usize>()?,
            maj_flt: columns[11].parse::<usize>()?,
            cmaj_flt: columns[12].parse::<usize>()?,
            utime: columns[13].parse::<usize>()?,
            stime: columns[14].parse::<usize>()?,
            cutime: columns[15].parse::<usize>()?,
            cstime: columns[16].parse::<usize>()?,
            priority: columns[17].parse::<usize>()?,
            nice: columns[18].parse::<usize>()?,
            num_threads: columns[19].parse::<usize>()?,
            it_real_value: columns[20].parse::<usize>()?,
            start_time: columns[21].parse::<usize>()?,
            vsize: columns[22].parse::<usize>()?,
            rss: columns[23].parse::<usize>()?,
            rlim: columns[24].parse::<usize>()?,
            start_code: columns[25].parse::<usize>()?,
            end_code: columns[26].parse::<usize>()?,
            start_stack: columns[27].parse::<usize>()?,
            kstkesp: columns[28].parse::<usize>()?,
            kstkeip: columns[29].parse::<usize>()?,
            pendingsig: columns[30].parse::<usize>()?,
            block_sig: columns[31].parse::<usize>()?,
            sigign: columns[32].parse::<usize>()?,
            sigcatch: columns[33].parse::<usize>()?,
            wchan: columns[34].parse::<usize>()?,
            nswap: columns[35].parse::<usize>()?,
            cnswap: columns[36].parse::<usize>()?,
            exit_signal: columns[37].parse::<usize>()?,
            task_cpu: columns[38].parse::<usize>()?,
            task_rt_priority: columns[39].parse::<usize>()?,
            task_policy: columns[40].parse::<usize>()?,
            blio_ticks: columns[41].parse::<usize>()?,
            gtime: columns[42].parse::<usize>()?,
            cgtime: columns[43].parse::<usize>()?,
            start_data: columns[44].parse::<usize>()?,
            end_data: columns[45].parse::<usize>()?,
            start_brk: columns[46].parse::<usize>()?,
            arg_start: columns[47].parse::<usize>()?,
            arg_end: columns[48].parse::<usize>()?,
            env_start: columns[49].parse::<usize>()?,
            env_end: columns[50].parse::<usize>()?,
            exit_code: columns[51].parse::<usize>()?,
        })
    }
}

pub fn stat_of(pid: u32) -> Result<Stat> {
    let content = std::fs::read_to_string(pid_path!(pid, "stat"))?;
    Stat::from_str(content.trim())
}
